import requests

# NodeMCU IP adresi ve endpoint
url = "http://192.168.1.37/upload/"  # NodeMCU'nun IP adresini yazın
headers = {'Content-Type': 'text/plain'}

# txt dosyasını okuma ve veriyi göndermek
# with open("emote_base64.txt", "r") as file:
#     data = file.read()

data = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//gAAAAAAAAAB//8AAAAH/B8AAAAAAAAAA+D/gAAAD/wPgAAAAAAAAAfA/8AAAA/8B4AAAAAAAAAHgP/AAAAf/gPAAAAAAAAADwH/4AAAH/4DwAAAAAAAAA8B/+AAAD/+A+AAAAAAAAAfAf/wAAA//gPgAAAAAAAAHwH/8AAAP/8B4AAAAAAAAB4D//AAAD//geAAAAAAAAAeB//wAAA//8HgAAAAAAAAHg//8AAAP///4AAAAAAAAB////AAAB///8AAAAAAAAAP///gAAAf/5/AAAAAAAAAD+f/4AAAD/8PgAAAAAAAAAfD/8AAAB/+D4AAAAAAAAAHwf/gAAA//g8ABgB/4AYAA8H/8AAAe//+AAYAf+AGAAH//3gAAPH//AAAwH/gMAAA//48AADh//AAGMB/4DGAAD/+HAAAAd/AABgAP8ABgAAP7gAAAAGGAAAAAA8AAAAAAYYAAAAABgAAAAAPAAAAAAGAAAAAAAAAAAGAH4AYAAAAAAAAAAAAAAABwH/gOAAAAAAAAAAAAAAAAeH5+HgAAAAAAAAAAAAAAAD/4H/wAAAAAAAAAAAAAAAAf4Af4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="


response = requests.post(url, headers=headers, data=data)

if response.status_code == 200:
    print("Veri başarıyla gönderildi.")
else:
    print(f"Veri gönderilirken bir hata oluştu: {response.status_code}")
